use std::process::Command;

/// This test implementation follows the "Golden Master TDD strategy" described in document 0019.
/// In a reverse engineering environment where traditional TDD is often impossible, we use
/// exact bitstream comparison against a Golden Master (known good fixture) as our assertion baseline.
#[test]
fn test_golden_master_strategy_framework() {
    // 1. Golden Master file (known correct file generated by the game)
    let golden_master = "tests/fixtures/savegames/original/amazon_empty.d2s";

    // 2. Our generation logic (pointing to same file for now as a framework demo)
    // Future: let actual_generated = generate_save_with_our_code(...);
    let actual_generated = "tests/fixtures/savegames/original/amazon_empty.d2s";

    // 3. Use d2save_item_diff to perform an isolated comparison of item bits
    let output = Command::new("cargo")
        .arg("run")
        .arg("-q")
        .arg("--bin")
        .arg("d2save_item_diff")
        .arg("--")
        .arg(actual_generated)
        .arg(golden_master)
        .output()
        .expect("Failed to execute d2save_item_diff");

    // 4. If even a single bit is wrong or padding is missing, this test must fail.
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        output.status.success() && stdout.contains("[IDENTICAL]"),
        "🚨 Golden Master Test Failed! The generated bits do not match the golden master.\nDiff Ouput:\n{}",
        stdout
    );
}

/// A failure case test demonstrating how the TDD framework detects known issues (like the 15-byte missing footer).
#[test]
fn test_detect_bit_shift_and_missing_bytes() {
    // Actual 10_scrolls fixture
    let golden_master = "tests/fixtures/savegames/original/amazon_10_scrolls.d2s";
    // An empty file which is guaranteed to fail bit-comparison against the 10-scrolls fixture
    let missing_bytes_file = "tests/fixtures/savegames/original/amazon_empty.d2s";

    let output = Command::new("cargo")
        .arg("run")
        .arg("-q")
        .arg("--bin")
        .arg("d2save_item_diff")
        .arg("--")
        .arg(missing_bytes_file)
        .arg(golden_master)
        .output()
        .expect("Failed to execute d2save_item_diff");

    // d2save_item_diff is designed to return non-zero (1) on mismatch.
    assert!(
        !output.status.success(),
        "This test should fail as the bitstreams are different!"
    );
}
