use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Serialize, Deserialize)]
struct Skill {
    pub skill: String,
    pub id: u32,
    pub charclass: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ItemData {
    pub name: Option<String>,
    pub code: String,
    pub invwidth: Option<u8>,
    pub invheight: Option<u8>,
    pub stackable: Option<u8>,
    pub nodurability: Option<u8>,
    pub durability: Option<u16>,
    pub is_armor: bool,
    pub is_weapon: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct StatCost {
    pub id: u32,
    pub name: String,
    pub save_bits: u8,
    pub save_param_bits: u8,
    pub save_add: i32,
}

fn main() {
    dotenvy::dotenv().ok();

    let d2data_dir = env::var("D2DATA_JSON_DIR").expect("D2DATA_JSON_DIR must be set in .env");
    let base_path = PathBuf::from(d2data_dir);

    extract_skills(&base_path);
    extract_item_codes(&base_path);
    extract_stat_costs(&base_path);
}

fn extract_skills(base_path: &PathBuf) {
    let mut source_path = base_path.clone();
    source_path.push("skills.json");
    if !source_path.exists() {
        return;
    }

    let file_content = fs::read_to_string(source_path).expect("Failed to read skills.json");
    let raw_data: HashMap<String, serde_json::Value> =
        serde_json::from_str(&file_content).expect("Failed to parse skills JSON");

    let mut warlock_skills = Vec::new();
    for (key, val) in raw_data {
        if key == "Expansion" {
            continue;
        }
        let id_num = key.parse::<u32>().unwrap_or(0);
        if val["charclass"].as_str() == Some("war") {
            warlock_skills.push(Skill {
                skill: val["skill"].as_str().unwrap_or("").to_string(),
                id: id_num,
                charclass: Some("war".to_string()),
            });
        }
    }
    warlock_skills.sort_by_key(|a| a.id);
    // println!("Found {} Warlock Skills.", warlock_skills.len());
}

fn extract_item_codes(base_path: &PathBuf) {
    let files = ["armor.json", "weapons.json", "misc.json"];
    let mut all_items = Vec::new();

    for file_name in files {
        let mut path = base_path.clone();
        path.push(file_name);
        if !path.exists() {
            continue;
        }

        let (is_armor, is_weapon) = match file_name {
            "armor.json" => (true, false),
            "weapons.json" => (false, true),
            _ => (false, false),
        };

        let content = fs::read_to_string(path).expect("Failed to read item file");
        let data: HashMap<String, serde_json::Value> =
            serde_json::from_str(&content).expect("Failed to parse item JSON");

        for (id, val) in data {
            if id == "Expansion" {
                continue;
            }
            let code = val["code"].as_str().unwrap_or("").trim().to_string();
            if code.is_empty() {
                continue;
            }
            all_items.push(ItemData {
                name: val["name"].as_str().map(|s| s.to_string()),
                code,
                invwidth: val["invwidth"].as_u64().map(|v| v as u8),
                invheight: val["invheight"].as_u64().map(|v| v as u8),
                stackable: val["stackable"].as_u64().map(|v| v as u8),
                nodurability: val["nodurability"].as_u64().map(|v| v as u8),
                durability: val["durability"].as_u64().map(|v| v as u16),
                is_armor,
                is_weapon,
            });
        }
    }

    let mut out = String::new();
    out.push_str("// Generated by d2r-data-extractor. DO NOT EDIT.\n\n");
    out.push_str(
        "pub struct ItemTemplate {\n    pub code: &'static str,\n    pub name: &'static str,\n    pub width: u8,\n    pub height: u8,\n    pub is_armor: bool,\n    pub is_weapon: bool,\n    pub is_stackable: bool,\n    pub has_durability: bool,\n}\n\n",
    );
    out.push_str("pub const ITEM_TEMPLATES: &[ItemTemplate] = &[\n");
    for item in all_items {
        let name = item
            .name
            .as_deref()
            .unwrap_or("Unknown")
            .replace('\"', "\\\"");
        let has_durability =
            item.durability.unwrap_or(0) > 0 || item.nodurability.unwrap_or(1) == 0;
        out.push_str(&format!(
            "    ItemTemplate {{ code: \"{}\", name: \"{}\", width: {}, height: {}, is_armor: {}, is_weapon: {}, is_stackable: {}, has_durability: {} }},\n",
            item.code,
            name,
            item.invwidth.unwrap_or(1),
            item.invheight.unwrap_or(1),
            item.is_armor,
            item.is_weapon,
            item.stackable.unwrap_or(0) != 0,
            has_durability,
        ));
    }
    out.push_str("];\n");

    let mut out_path = PathBuf::from("..");
    out_path.push("src");
    out_path.push("data");
    fs::create_dir_all(&out_path).ok();
    out_path.push("item_codes.rs");
    fs::write(&out_path, out).expect("Failed to write item_codes.rs");
}

fn extract_stat_costs(base_path: &PathBuf) {
    let mut source_path = base_path.clone();
    source_path.push("itemstatcost.json");
    if !source_path.exists() {
        return;
    }

    let content = fs::read_to_string(source_path).expect("Failed to read itemstatcost.json");
    let data: HashMap<String, serde_json::Value> =
        serde_json::from_str(&content).expect("Failed to parse stat costs JSON");

    let mut stats = Vec::new();
    for (name, val) in data {
        if name == "Expansion" || name == "lineNumber" {
            continue;
        }
        let id = val["*ID"].as_u64().unwrap_or(u64::MAX) as u32;
        if id == u32::MAX {
            continue;
        }

        stats.push(StatCost {
            id,
            name,
            save_bits: val["Save Bits"].as_u64().unwrap_or(0) as u8,
            save_param_bits: val["Save Param Bits"].as_u64().unwrap_or(0) as u8,
            save_add: val["Save Add"].as_i64().unwrap_or(0) as i32,
        });
    }
    stats.sort_by_key(|s| s.id);

    let mut out = String::new();
    out.push_str("// Generated by d2r-data-extractor. DO NOT EDIT.\n\n");
    out.push_str("pub struct StatCost {\n    pub id: u32,\n    pub name: &'static str,\n    pub save_bits: u8,\n    pub save_param_bits: u8,\n    pub save_add: i32,\n}\n\n");
    out.push_str("pub const STAT_COSTS: &[StatCost] = &[\n");
    for s in stats {
        out.push_str(&format!(
            "    StatCost {{ id: {}, name: \"{}\", save_bits: {}, save_param_bits: {}, save_add: {} }},\n",
            s.id, s.name, s.save_bits, s.save_param_bits, s.save_add
        ));
    }
    out.push_str("];\n");

    let mut out_path = PathBuf::from("..");
    out_path.push("src");
    out_path.push("data");
    out_path.push("stat_costs.rs");
    fs::write(&out_path, out).expect("Failed to write stat_costs.rs");
    println!("Generated: {}", out_path.display());
}
